build site:
  image: node:9
  stage: build
  script:
    - yarn install --progress=false
    - yarn run build
  artifacts:
    expire_in: 1 week
    paths:
      - build

deploy:
  image: docker
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - docker build -t node_prod_image -f docker/Dockerfile.prod .
    - docker save node_prod_image | ssh $SSH_HOST "docker load"

