version: '2'

services:
  app:
    build:
      dockerfile: docker/Dockerfile
      context: .
    command: npm start
    ports:
      - 127.0.0.1:3020:3020
    volumes:
      - .:/app
      # exclude folder from volume https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
      - /app/node_modules

    env_file: .env
    
    environment:
      - DB_HOST=db

    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
      
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=example_db