version: '2'

services:
  app:
    build:
      dockerfile: docker/Dockerfile
      context: .
    command: npm run dev
    ports:
      # Make docker machine listening on 0.0.0.0 (direct access e.g from wifi)
      # https://www.reddit.com/r/docker/comments/731cop/docker_compose_change_default_ip_from_0000/
      - 0.0.0.0:2020:2020
    volumes:
      - .:/app
      # exclude folder from volume https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
      # - /app/node_modules

    # Do we need it?
    # env_file: .env

    environment:
      # Do I need this?
      - POSTGRES_HOST=db

    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=node_boilerplate_local
