region  = "eu-central-1"
domain  = "dailyfaily.com"
project = "node-graphql-boilerplate"
environment    = "stage_1"
url_prefix    = "stage-1"


# region  = "eu-central-1"
# domain  = "dailyfaily.com"
# project = "node-graphql-boilerplate"
# stage_1_environment    = "stage_1"
# stage_1_url_prefix    = "stage-1"
# stage_2_environment    = "stage_2"
# stage_2_url_prefix    = "stage-2"
# production_environment    = "production"
# production_url_prefix    = "production"