# this dockerfile is for prod instance

FROM keymetrics/pm2:latest-alpine

# copy whole project (except .dockerignore) to docker machine
COPY . /usr/app/

WORKDIR /usr/app

# install libs
RUN yarn


# build app
RUN yarn run build

EXPOSE 3020

CMD ["pm2-runtime", "process.yml"]